### ISSUE TITLE
Mis-specified header for continuous files

### ISSUE THREAD

**Issue by paf1984** [open-ephys-plugins/open-ephys-data-format#1]
I think there is an error at Line 79.

Missing on the preceding line: header += "header.sampleRate = ";

Which leads to incorrectly specified headers in .continous files:

See below:

header.channel = 'ADC1';
header.channelType = 'Continuous';
12500;
header.blockLength = 1024;

which is missing header.sampleRate = prior to the sample rate value

This prevents some third party software (and some matlab scripts) from correctly parsing .continous files.

**Comment by medengineer** [comment]
Fixed w/ commit d77928f

**Comment by jsiegle** [comment]
Thanks for pointing this out! If you upgrade to the latest version of the Open Ephys Data Format (0.6.2) using the Plugin Installer, the header files should be written correctly.
